### ISSUE TITLE
rethink schema types

### ISSUE THREAD

**Issue by sevko** [pelias/schema#48]
[We currently define](https://github.com/pelias/schema/blob/master/schema.js#L7,L23) elasticsearch types on a per-dataset basis, so things like GeoNames, OpenAddresses, and OSM all have an individual type (OSM has multiple, in fact: `osmaddress`, `osmnode`, and `osmway`). The majority of these are all aliases for the [`poi` mapping](https://github.com/pelias/schema/blob/master/mappings/poi.js), which just defines a named point, which begs the question why we're bothering with a type per dataset to begin with. I believe it'd be better to have just, say, three types - `point` (addresses/POIs), `street`, and `boundary` (administrative polygons) - for the following reasons:

1. ease of use: this is really the biggest selling point. If someone wants to index a new dataset in Pelias, they either need to add a new type to the schema or use one of the existing ones. The problem here is that the user needs to *learn* about the different types, and we need to document that we have a type per dataset (and I don't think there's a clear reason why that is... we just *do*). People would then have to locally modify `pelias-schema` and recreate the index. Moreover, people won't *get* the different types right off the bat: what are `openaddresses`, `geonames`, `admin1`, etc? Then they have to go understand the POI mapping, and so on. It'd be much more intuitive for people to deal with types like `point` and `street`, because it should usually be painfully clear what kind of data you have, and those don't require much explanation.

2. clarity: this was touched on in the previous point, but the *type* of data seems like a much stronger cause for separation into different elasticsearch types than its *origin*. It makes sense to separate administrative polygons from addresses/POIs from street linestrings. I don't think it makes *as much* sense to segregate them by data-source, which seems rather secondary.

Here are the downsides:

1. we lose the ability to remove a specific dataset by just dropping a type. Kind of a non-issue, since we can just write an ES query to do the same thing and bundle that into a script.

2. we'll have to:
  1. change record GUIDs: we currently generate pseudo-GUIDs in a variety of ways that differ by dataset (some just use an incremented integer). We'd need to write a separate Transform stream that creates uniform ids for all datasets that are guaranteed to be unique in their elasticsearch type. I'm envisioning this as a separate step of the imports:
  
  ```javascript
  .pipe(peliasSuggester.pipeline)
  .pipe(peliasDocumentGuid()) // <--- record ID set here
  .pipe(peliasDbclient())
  ```

    It might just implement something like `[esType, originDataset, localId++].join(":")`, to generate IDs that look like `point.openstreetmap.1`, `street.tiger.3`, `boundary.quattroshapes.59`, ...

  2. update `pelias-schema`, and changing the type names referenced by all of our importers.
  3. update our queries ( @hkrishna , how extensive would this be?)

**Comment by missinglink** [comment]
This is a super-important decision and so I've been mulling over my response for some time, so firstly apologies for the delay.

Your question of `"why we're bothering with a type per dataset to begin with?"` is a valid question.

In the very beginning of the project the main focus was on sourcing all the open-data we could and getting it in to elasticsearch and so partitioning data in this way made complete sense.

The current `_type` structure made adding new datasets simpler as it did not require dropping `quattroshapes` and other datasets when developing importers for newer datasets (such as `osm`).

I think your proposed solution above in `downsides:1` could provide a nice analog for this behaviour.

It also meant that during the early stages when the schema changed very often, we had the ability to add/remove/modify fields in the mapping without having to delete unrelated data from the index.

My gut feeling is that making any non-trivial modifications to a `_type` mapping will always require a complete re-index of that whole `_type`, this is just the nature of the beast and so when discussing how best to use `_type` to partition our data, this limitation must be considered.

Your first point about `ease of use` is certainly true, expecting new developers to understand that they *must* add a new `_type` mapping in order to index their new dataset is not very intuitive, plus they might want to modify `pelias/api` to get that dataset added to a `layer alias`. It was certainly not intended to be complex and my thoughts in the past have been around using a `pelias binary` to solve these issues, which is also not a great solution.

This PR may go a long way to resolving this problem: https://github.com/pelias/schema/pull/53

To address your second point `clarity`, I tend to agree. I'm still unsure on how important it will be for developers who need to keep `open/proprietary` data separate or are prevented from mixing datasets in the results for licensing reasons.

In regards to the cons, this will require significant changes to the code base, across many repositories and may result in downtime or at very least a slowdown in feature development while the changes stabilize.

The global ids will need certainly to change which will result in a breaking API change, although I don't think this is a big deal at this stage. The global ids would need to be a concatenation of 3 identifiers rather than 2.

In recent iterations we have been moving away from differentiating between `point` and `boundary` data in favour of a more generic homogenised mapping. This is the result of no longer storing `quattroshapes` geometry in elasticsearch and also the PR I mentioned above.

We've also recently discussed that storing `street` geometry in elasticsearch may only be useful for rendering simplified polygons in the front-end, which would also be nice for `boundaries`. If we were to going to import the street geometry for use in query-time calculations for intersections and interpolations then there may be additional value in partitioning the data to accommodate that more easily.

---

Since it's super-important to get this right and when it's changed will have an non-trivial impact to both the private and public APIs I would like to open up this discussion to explore *all* the options for "what to use _type for?".

I see `_type` as roughly equivalent to a `table` in a traditional relational `database`, in that it is the highest level partitioning of data *within* a database structure.

There are also many ways of partitioning data lower down such as simple queries like `SELECT * FROM mytable WHERE mycolumn = 'foo';` and other exclusionary filters. These filters are highly optimised and so therefore are generally very efficient (on indexed values) but tend to add complexity when composing complex queries.

In your comments above you mentioned that you would like to move to a structure where the highest level partitions of the pelias index would be to represent `point`, `street` and `boundary` as the 3x core`type`s.

I'd also like to consider using `_type` for partitioning data by `language` and other metrics.
There may be a strong case in favour of partitioning by `language`, `_type` is related to the internal Lucene data structure which are directly tied to things like inverse document frequency.

A simple example is the word 'die' in English is a verb to kill someone but in German it's a very common noun equivalent to 'The'. If we used `_type` to partition by language would analysis be easier and make it simpler and more culturally relevant when using an autocomplete in different languages?

It's also worth discussing using a different `_index` for these things, as the highest level of partitioning data, equivalent to storing in a different `database` completely, what affect would that have on query performance etc. Is that something worth considering?

**Comment by sevko** [comment]
The move to a single mapping in #53 has indeed done quite a bit to simplify this issue. I'm curious what @hkrishna has to say about what kinds of different `_type`s would allow improved/simplified search logic? I proposed the `point`, `street`, and `boundary` types because those seem to be the bread-and-butter categories of geographic data, but we should definitely explore any other options.

**Comment by missinglink** [comment]
I had an epiphany today about how to make setting up a new layer totally painless.

Instead of having 'poi', 'address' and 'admin' data, we could define their class as a `category` tag, which would make data from new layers appear in the API 'aliases' automagically with a little minor tweaking to the API code.

Then since all `_type` mappings are essentially the same, we could define a [_default_](http://www.elastic.co/guide/en/elasticsearch/guide/master/default-mapping.html) mapping which all new types will inherit, which results in the new layer not having to mess around with `pelias/schema` at all.

This however, will not work with `/suggest` until the category suggester gets updated in elasticsearch@v2.0 shipping soon.

**Comment by sevko** [comment]
> will not work with `/suggest`

This only applies to filtering results with the `layers` param, right?

**Comment by missinglink** [comment]
nope, that would still work fine because we can use `_type` as the filter; which `es:9200/_suggest` supports.

...come to think of it, this would work fine for `/_suggest` with the caveat that the hard-coded mapping of `layer_name->alias` would have to remain until es@2.0 when that can also be removed.

**Comment by sevko** [comment]
I'd argue the schema change should go into Pelias v1.0.0, then.
