### ISSUE TITLE
Storing names in elasticsearch

### ISSUE THREAD

**Issue by missinglink** [pelias/schema#49]
We currently have all place names stored as key/value pairs under the `.name` property.

A single entity can have many different names (different languages, common names etc).

This OSM record is a good example:
http://www.openstreetmap.org/way/238241022
http://pelias.mapzen.com/doc?id=osmway:238241022

| name    | The White House |
|---------|-----------------|
| name:de | Weißes Haus     |
| name:fa | کاخ سفید        |

The options for storing the data in Elasticsearch are:

#### one property per name on the document root.
```javascript
document.name_default = "The White House"
document.name_fa = "کاخ سفید"
```
This approach would require each property to be explicitly defined at query time in order to tell elasticsearch which properties to search on. Is it possible to alias them?

#### an array of names:
```javascript
document.name = [ "The White House", "Weißes Haus", "کاخ سفید" ]
```
This approach removes the name keys, which means we no longer have any way of telling the origin language and the 'default' name. It makes searching much easier.

#### a dictionary of names:
```javascript
document.name = {
  default: "The White House",
  de: "Weißes Haus",
  fa: "کاخ سفید"
}
```
This is how we current have it configured, it allows us to keep both the key and the value while also allowing us to add/remove elements from the schema. The disadvantage is that you cannot simply query `document.name`, you MUST query `document.name.default` or explicitly specify all fields (as above). It also means that the naming schema is not well documented and (besides `name.default`) can contain arbitrary keys (which makes it harder to query).

This ticket is opened in order to establish that the dictionary approach is the best option and/or to discuss alternate ways of storing names in order to make them easier to search.

**Comment by missinglink** [comment]
Another thing to consider is inverse document frequencies for languages, an example is 'die' in german means 'the' and therefore should be considered unimportant and discarded by the tokenizer, however! the word 'die' in the english language is less common and should be included in the tokens.

The Photon project partitions it's data by language in order to specify different analysers per language, this may be a logic next step for Pelias as we start to tackle i18n.

**Comment by missinglink** [comment]
hk mentioned that we can use `multi_match` queries to solve some of these problems, regardless of the implementation we choose.

```javascript
{
  "multi_match" : {
    "query":    “foo", 
    "fields": [ “name.*" ] 
  }
}
```

**Comment by sevko** [comment]
The dictionary of names seems the most reasonable. I dislike the idea of making the names top level properties, since having a bunch of keys named `name_fr`, `name_en`, `name_${LANGUAGE}`, etc. seems like a natural reason to use an object. You can't define the specific properties that it can have, right? ie, the most that you can do is specify that `name` is an object, and as far as elasticsearch is concerned it can contain anything you fancy. If that's the case, it's not a huge problem because we can restrict the settable names inside `pelias-model`, but that's not ideal (though it might still be the best solution).

**Comment by dianashk** [comment]
I like what we are currently doing for all the reasons everyone has already mentioned. I've updated `/search` to use `multi_match` so that should alleviate some of the concerns here.

We should analyze each language field differently as mentioned [here](http://www.elastic.co/guide/en/elasticsearch/guide/master/one-lang-fields.html), given that we know which language it maps to. Will need to make assumptions about name.default based on admin lookup results.

**Comment by missinglink** [comment]
I'm pretty confident that the `object` type is the correct field type to use now that I understand how to use `dynamic_templates` to assign `analyzers` to dynamically added properties.

https://github.com/pelias/playground/blob/master/dynamic_templates.js
http://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-root-object-type.html#_dynamic_templates
