### ISSUE TITLE
refresh interval

### ISSUE THREAD

**Issue by heffergm** [pelias/schema#57]
Set the refresh_interval of the pelias index directly when creating the schema:

settings.js:

```json
    },
    "index": {
      "number_of_replicas": "0",
      "number_of_shards": "1",
      "refresh_interval": "1m",
```

Allow override in the usual fashion via PELIAS_CONFIG.

**Comment by missinglink** [comment]
I checked the code and the whole `"index"` object including any properties such as `"refresh_interval"` is already over-ridable via `PELIAS_CONFIG`.

The config currently doesn't specify a default setting for `"refresh_interval"` so it will default to whatever the default value is for the elasticsearch version you are running (which is `1s` since forever)

There was a old discussion about this issue where I added some comments: https://github.com/pelias/schema/issues/27

**Comment by heffergm** [comment]
Sounds good.
